const UPDATE_ANSWER = 'UPDATE_ANSWER';
const ADD_ANSWER = 'ADD_ANSWER';
const CLEAR_ANSWERS = 'CLEAR_ANSWERS';
const CHANGE_CONTENT = 'CHANGE_CONTENT';
const CLEAR_RESULT = 'CLEAR_RESULT';
const UPDATE_RESULT = 'ADD_RESULT';

const types = { UPDATE_ANSWER, CHANGE_CONTENT, UPDATE_RESULT, ADD_ANSWER, CLEAR_ANSWERS, CLEAR_RESULT }

export default types;