const UPDATE_ANSWER = 'UPDATE_ANSWER';
const ADD_ANSWER = 'ADD_ANSWER';
const CHANGE_CONTENT = 'CHANGE_CONTENT';
const UPDATE_RESULT = 'ADD_RESULT';

const types = { UPDATE_ANSWER, CHANGE_CONTENT, UPDATE_RESULT, ADD_ANSWER }

export default types;