const ADD_ANSWER = 'ADD_ANSWER';
const UPDATE_ANSWER = 'UPDATE_ANSWER';
const CHANGE_CONTENT = 'CHANGE_CONTENT';

const types = { ADD_ANSWER, UPDATE_ANSWER, CHANGE_CONTENT }

export default types;